-- ingestion-service schema (database: jarvis_ingestion). Owns the raw alert audit log.

CREATE TABLE raw_message (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source           VARCHAR(20)  NOT NULL,
    payload          TEXT         NOT NULL,
    sender           VARCHAR(320),
    received_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    status           VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    transaction_ref  BIGINT,      -- id of the transaction created in expense-service (no FK across DBs)
    error            TEXT,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_raw_message_status ON raw_message (status);
