-- The assistant's conversations. One row per chat, one row per turn inside it, so a past chat can
-- be reopened and carried on where it stopped.
--
-- Scoped by username rather than member id: a chat belongs to whoever typed it, and a household
-- member signing in only ever sees their own. Nothing here is shared, not even with the admin.
CREATE TABLE chat_session (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(120) NOT NULL,
    -- Taken from the first question asked, so the list reads like the conversation it opens.
    title       VARCHAR(160) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- The list is always "my chats, newest first".
CREATE INDEX idx_chat_session_user ON chat_session (username, updated_at DESC);

CREATE TABLE chat_message (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT       NOT NULL REFERENCES chat_session (id) ON DELETE CASCADE,
    role        VARCHAR(16)  NOT NULL,   -- user | assistant
    body        TEXT         NOT NULL,
    -- A proposed action, exactly as the web app rendered it, so a reopened chat can still show the
    -- card - and still run it, if it was never confirmed.
    action_json TEXT,
    status      VARCHAR(16),             -- pending | done | cancelled | failed
    result      TEXT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Read back in the order it was said.
CREATE INDEX idx_chat_message_session ON chat_message (session_id, id);
