-- User-defined categorisation: "merchant contains <pattern>" → category. Applied to new alerts
-- (a rule beats the AI's guess) and, on demand, to existing transactions.
CREATE TABLE category_rule (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern     VARCHAR(120) NOT NULL,
    category    VARCHAR(80)  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
