-- Bank alerts name the same shop many different ways ("AMAZON PAY", "AMAZON PAY IN",
-- "AMAZON PAY IN GROCERY"), which splits one merchant across several rows in every breakdown.
-- An alias maps the raw string to a clean name, and optionally to the category it belongs in.
CREATE TABLE merchant_alias (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw        VARCHAR(256) NOT NULL UNIQUE,
    canonical  VARCHAR(128) NOT NULL,
    category   VARCHAR(64),
    -- "ai" when suggested by the model and accepted, "user" when typed by hand.
    source     VARCHAR(16)  NOT NULL DEFAULT 'user',
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- The clean name, copied onto the transaction so grouping stays a plain column read.
ALTER TABLE transaction ADD COLUMN merchant_norm VARCHAR(128);
CREATE INDEX idx_txn_merchant_norm ON transaction (merchant_norm);
