-- finance-service schema (shared jarvis DB). Owns members, investments, loans, reminders, thresholds.

CREATE TABLE member (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    relation  VARCHAR(64)  NOT NULL DEFAULT 'Self',
    email     VARCHAR(320)
);

CREATE TABLE investment (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id          BIGINT NOT NULL REFERENCES member (id) ON DELETE CASCADE,
    kind               VARCHAR(8)   NOT NULL,
    name               VARCHAR(255) NOT NULL,
    principal          NUMERIC(16, 2) NOT NULL DEFAULT 0,
    current_value      NUMERIC(16, 2) NOT NULL DEFAULT 0,
    rate               DOUBLE PRECISION,
    sip                NUMERIC(16, 2),
    opening_date       DATE,
    commencement_date  DATE,
    maturity_date      DATE,
    notes              TEXT
);
CREATE INDEX idx_investment_member ON investment (member_id);

CREATE TABLE loan (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id      BIGINT NOT NULL REFERENCES member (id) ON DELETE CASCADE,
    kind           VARCHAR(12)  NOT NULL,
    lender         VARCHAR(255) NOT NULL,
    sanctioned     NUMERIC(16, 2) NOT NULL DEFAULT 0,
    outstanding    NUMERIC(16, 2) NOT NULL DEFAULT 0,
    emi            NUMERIC(16, 2) NOT NULL DEFAULT 0,
    rate           DOUBLE PRECISION,
    tenure_months  INTEGER,
    start_date     DATE,
    end_date       DATE,
    notes          TEXT
);
CREATE INDEX idx_loan_member ON loan (member_id);

CREATE TABLE reminder (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(255) NOT NULL,
    due_date       DATE NOT NULL,
    reminder_type  VARCHAR(16)  NOT NULL,
    amount         NUMERIC(16, 2),
    notes          TEXT,
    repeat_mode    VARCHAR(12)  NOT NULL DEFAULT 'none'
);

CREATE TABLE category_threshold (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category  VARCHAR(255) NOT NULL,
    amount    NUMERIC(16, 2) NOT NULL DEFAULT 0,
    CONSTRAINT uq_category_threshold UNIQUE (category)
);
