-- Savings goals (e.g. emergency fund, a trip): track progress toward a target amount by a date.
CREATE TABLE goal (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    target_amount  NUMERIC(16, 2) NOT NULL DEFAULT 0,
    saved_amount   NUMERIC(16, 2) NOT NULL DEFAULT 0,
    target_date    DATE,
    color          VARCHAR(16),
    notes          TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
