-- Marking a reminder occurrence as paid by hand. Needed because a reminder without an amount
-- (an electricity bill that varies each month) can never be closed by matching a transaction.
-- One row per occurrence, so a monthly reminder closes month by month.
CREATE TABLE reminder_payment (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reminder_id    BIGINT       NOT NULL REFERENCES reminder (id) ON DELETE CASCADE,
    occurred_on    DATE         NOT NULL,
    paid_on        DATE         NOT NULL,
    amount         NUMERIC(16, 2),
    transaction_id BIGINT,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_reminder_payment UNIQUE (reminder_id, occurred_on)
);
