-- notification-service schema (shared jarvis DB). Owns the bell's notification feed.
CREATE TABLE notification (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        VARCHAR(16)  NOT NULL,
    title       VARCHAR(255) NOT NULL,
    message     VARCHAR(512) NOT NULL,
    href        VARCHAR(64)  NOT NULL DEFAULT '/dashboard',
    color       VARCHAR(16)  NOT NULL DEFAULT '#6366f1',
    dedupe_key  VARCHAR(128) NOT NULL,
    is_read     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_notification_dedupe UNIQUE (dedupe_key)
);
CREATE INDEX idx_notification_created ON notification (created_at DESC);
