-- Jarvis Phase 1 schema: accounts, categories, raw messages, transactions.

CREATE TABLE account (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank          VARCHAR(255) NOT NULL,
    type          VARCHAR(20)  NOT NULL,
    last4         VARCHAR(4)   NOT NULL,
    display_name  VARCHAR(255) NOT NULL,
    currency      VARCHAR(3)   NOT NULL DEFAULT 'INR',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_account_bank_last4_type UNIQUE (bank, last4, type)
);

CREATE TABLE category (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    parent_id  BIGINT REFERENCES category (id),
    CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE raw_message (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source       VARCHAR(20)  NOT NULL,
    payload      TEXT         NOT NULL,
    sender       VARCHAR(320),
    received_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    status       VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    error        TEXT,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE transaction (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id      BIGINT REFERENCES account (id),
    amount          NUMERIC(14, 2) NOT NULL,
    currency        VARCHAR(3)     NOT NULL DEFAULT 'INR',
    direction       VARCHAR(10)    NOT NULL,
    merchant        VARCHAR(256),
    category_id     BIGINT REFERENCES category (id),
    occurred_at     TIMESTAMPTZ    NOT NULL,
    source          VARCHAR(20)    NOT NULL,
    raw_message_id  BIGINT REFERENCES raw_message (id),
    dedup_hash      VARCHAR(64),
    note            TEXT,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT uq_transaction_dedup_hash UNIQUE (dedup_hash)
);

CREATE INDEX idx_txn_occurred_at ON transaction (occurred_at);
CREATE INDEX idx_txn_account     ON transaction (account_id);

-- Seed a small starter category tree (parents first).
INSERT INTO category (name) VALUES
    ('Food'), ('Shopping'), ('Bills & Utilities'), ('Transport'),
    ('Entertainment'), ('Health'), ('Transfers'), ('Income'), ('Uncategorized');
