-- Authentication: a single app user to start (schema supports more).

CREATE TABLE app_user (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR(100) NOT NULL,
    password_hash  VARCHAR(100) NOT NULL,
    roles          VARCHAR(255) NOT NULL DEFAULT 'USER',
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_app_user_username UNIQUE (username)
);
