-- User profile + extra bank/card fields on account.

CREATE TABLE user_profile (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL REFERENCES app_user (id),
    full_name      VARCHAR(255),
    email          VARCHAR(320),
    phone          VARCHAR(32),
    base_currency  VARCHAR(3) DEFAULT 'INR',
    city           VARCHAR(120),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_user_profile_user UNIQUE (user_id)
);

ALTER TABLE account
    ADD COLUMN network            VARCHAR(20),
    ADD COLUMN card_holder_name   VARCHAR(255),
    ADD COLUMN credit_limit       NUMERIC(14, 2),
    ADD COLUMN billing_cycle_day  INTEGER,
    ADD COLUMN payment_due_day    INTEGER,
    ADD COLUMN expiry_month       INTEGER,
    ADD COLUMN expiry_year        INTEGER,
    ADD COLUMN ifsc               VARCHAR(11),
    ADD COLUMN branch             VARCHAR(255);
