-- auth-service schema (database: jarvis_auth). Owns users + profile.

CREATE TABLE app_user (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR(100) NOT NULL,
    password_hash  VARCHAR(100) NOT NULL,
    roles          VARCHAR(255) NOT NULL DEFAULT 'USER',
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_app_user_username UNIQUE (username)
);

CREATE TABLE user_profile (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL REFERENCES app_user (id),
    full_name      VARCHAR(255),
    email          VARCHAR(320),
    phone          VARCHAR(32),
    base_currency  VARCHAR(3) DEFAULT 'INR',
    city           VARCHAR(120),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_user_profile_user UNIQUE (user_id)
);
