-- Per-user app preferences (emergency reserve, card reward rates, dashboard toggles …) so
-- nothing personal lives only in a browser. Values are JSON, keyed by a short dotted name.
CREATE TABLE user_preference (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    pref_key    VARCHAR(80)  NOT NULL,
    value_json  TEXT         NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_user_preference UNIQUE (user_id, pref_key)
);
